version: '3'
services:
  backend_server:
    image: hacku-2024-myj-backend-server
    build: .
    volumes:
      - .:/app
    ports:
      - '8000:8000'
    environment:
      - TZ=Asia/Tokyo
  db:
    image: mysql:8.0-debian
    platform: linux/x86_64
    env_file:
      - .env
    environment:
      - TZ=Asia/Tokyo
    ports:
      - '3306:3306'
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
